AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'test/support/**/*'

  DisplayCopNames: true

  DisplayStyleGuide:
    Enabled: true

Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 120
