AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'vendor/**/*'
    - 'test/support/**/*'

  DisplayCopNames: true

  DisplayStyleGuide:
    Enabled: true

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 120
