#!/usr/bin/env ruby
# frozen_string_literal: true

require 'erb'
require 'yaml'

`lpass sync`

YAML.safe_load(`lpass show pinboard-fixup-tweets --notes`).each do |k, v|
  Object.const_set(k, v)
end

puts ERB.new(DATA.read).result

__END__
#!/bin/sh

docker run --rm \
    --env TWITTER_CONSUMER_KEY=<%= TWITTER_CONSUMER_KEY %> \
    --env TWITTER_CONSUMER_SECRET=<%= TWITTER_CONSUMER_SECRET %> \
    --env PINBOARD_API_TOKEN=<%= PINBOARD_API_TOKEN %> \
    --name pinboard-fixup-github-titles \
  nerab/pinboard-fixup-tweets:latest
